name: registro_elettronico
description: Better and faster of the original.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.0.0+15

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0-nullsafety.0
  collection: ^1.15.0
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0
  dio: ^4.0.0
  expandable: ^5.0.1
  f_logs: ^2.0.0
  fimber: ^0.6.1
  firebase_analytics: ^8.3.2
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  firebase_messaging: ^10.0.7
  fl_chart: ^0.40.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_circular_chart_two:
    git:
      url: https://github.com/bradintheusa/flutter_circular_chart
  flutter_colorpicker: ^0.6.0
  flutter_email_sender: ^5.0.2
  flutter_local_notifications: ^8.2.0
  flutter_localizations:
    sdk: flutter
  flutter_search_bar: ^3.0.0-dev.1
  flutter_secure_storage: ^4.2.1
  flutter_speed_dial: ^4.4.0+1
  flutter_svg: ^0.22.0
  # flutter_webview_plugin: ^0.4.0
  get_it: ^7.2.0
  internet_connection_checker: ^0.0.1+2
  intl: ^0.17.0
  moor: ^4.5.0
  moor_db_viewer: ^4.4.0
  numberpicker: ^2.1.1
  open_file: ^3.2.1
  package_info: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.0
  pedantic: ^1.11.1
  percent_indicator: ^3.0.1
  pull_to_refresh: ^2.0.0
  responsive_framework: ^0.1.4
  rxdart: ^0.27.2
  screenshot: ^1.2.3
  share: ^2.0.4
  shared_preferences: ^2.0.8
  sqlite3_flutter_libs: ^0.5.0
  table_calendar: ^3.0.2
  timetable: ^1.0.0-alpha.5
  timezone: ^0.8.0
  tinycolor2:
    git:
      url: https://github.com/TinyCommunity/tinycolor2
  url_launcher: ^6.0.12
  webview_flutter: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter
  moor_generator: ^4.5.1

flutter:
  assets:
    - assets/icons/
    - assets/icons/subjects/
    - lang/en.json
    - lang/it.json

  uses-material-design: true
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Heavy.ttf
          weight: 900
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 200
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 300
    # - family: Montserrat
    #   fonts:
    #     - asset: assets/fonts/Montserrat-Regular.otf
    #     - asset: assets/fonts/Montserrat-Bold.otf
    #       weight: 700
    #     - asset: assets/fonts/Montserrat-Black.otf
    #       weight: 800
    #     - asset: assets/fonts/Montserrat-ExtraBold.otf
    #       weight: 900
    #     - asset: assets/fonts/Montserrat-Italic.otf
    #       style: italic
    #     - asset: assets/fonts/Montserrat-Light.otf
    #       weight: 200
    #     - asset: assets/fonts/Montserrat-Regular.otf
    #       weight: 400
    #     - asset: assets/fonts/Montserrat-Medium.otf
    #       weight: 300
