name: registro_elettronico
description: Better and faster of the original.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.5.1+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  f_logs:
    git:
      url: https://github.com/Saerlig-Software-Development/Flogs
  time_machine:
    git:
      url: https://github.com/Dana-Ferguson/time_machine
      ref: 7753e0d
  timetable:
    git:
      url: https://github.com/Saerlig-Software-Development/timetable
  auto_size_text: ^2.1.0
  collection: ^1.15.0
  cupertino_icons: null
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  dio: ^3.0.10
  esys_flutter_share: ^1.0.2
  expandable: ^5.0.1
  firebase_analytics: ^7.1.1
  firebase_core: ^1.0.1
  firebase_crashlytics: ^1.0.0
  firebase_messaging: ^9.0.0
  fl_chart: ^0.20.1
  flutter_bloc: ^7.0.0
  flutter_circular_chart: ^0.1.0
  flutter_colorpicker: ^0.3.5
  flutter_email_sender: ^5.0.0
  flutter_local_notifications: ^4.0.1+2
  flutter_search_bar: ^2.1.0
  flutter_secure_storage: ^4.1.0
  flutter_svg: null
  flutter_webview_plugin: ^0.3.11
  get_it: ^6.0.0
  intl: ^0.17.0
  moor: ^4.1.0
  moor_db_viewer: ^3.0.0
  numberpicker: ^1.3.0
  open_file: ^3.1.0
  package_info: ^2.0.0
  path_provider: ^1.6.24
  pedantic: ^1.11.0
  percent_indicator: ^2.1.9+1
  pull_to_refresh: ^1.6.4
  rxdart: ^0.26.0
  screenshot: ^0.2.0
  shared_preferences: ^0.5.12+4
  sqlite3_flutter_libs: null
  table_calendar: ^2.3.3
  tinycolor: ^1.0.3
  tuple: ^2.0.0
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  moor_generator: null

dependency_overrides:
  time_machine:
    git:
      url: https://github.com/Dana-Ferguson/time_machine
      ref: 7753e0d
  # Override for `flutter_local_notifications`:
  plugin_platform_interface: ^2.0.0

flutter:
  assets:
    - assets/icons/
    - assets/icons/subjects/
    - lang/en.json
    - lang/it.json
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin

  uses-material-design: true
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Heavy.ttf
          weight: 900
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 200
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 300
    # - family: Montserrat
    #   fonts:
    #     - asset: assets/fonts/Montserrat-Regular.otf
    #     - asset: assets/fonts/Montserrat-Bold.otf
    #       weight: 700
    #     - asset: assets/fonts/Montserrat-Black.otf
    #       weight: 800
    #     - asset: assets/fonts/Montserrat-ExtraBold.otf
    #       weight: 900
    #     - asset: assets/fonts/Montserrat-Italic.otf
    #       style: italic
    #     - asset: assets/fonts/Montserrat-Light.otf
    #       weight: 200
    #     - asset: assets/fonts/Montserrat-Regular.otf
    #       weight: 400
    #     - asset: assets/fonts/Montserrat-Medium.otf
    #       weight: 300
